const items = [
  {
    id: "ITEM1",
    name: "Potion",
    rarity: "Common",
    useInBattle: true,
    useFromMenu: true,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Heals Pokemon by 10",
  },
  {
    id: "ITEM2",
    name: "Super Potion",
    rarity: "Rare",
    useInBattle: true,
    useFromMenu: true,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Heals Pokemon by 20",
  },
  {
    id: "ITEM3",
    name: "Hyper Potion",
    rarity: "Epic",
    useInBattle: true,
    useFromMenu: true,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Heals Pokemon by 30",
  },
  {
    id: "ITEM4",
    name: "Max Potion",
    rarity: "Legendary",
    useInBattle: true,
    useFromMenu: true,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Heals Pokemon by 50",
  },
  {
    id: "ITEM5",
    name: "Rare Candy",
    rarity: "Legendary",
    useInBattle: false,
    useFromMenu: true,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Increases a pokemon's stage by 1",
  },
  {
    id: "ITEM6",
    name: "Plus Power",
    rarity: "Rare",
    useInBattle: true,
    useFromMenu: false,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Adds 10 to this attack if it is successful",
  },
  {
    id: "ITEM7",
    name: "Item Finder",
    rarity: "Epic",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: true,
    autoApply: false,
    text: "Reveal one card when choosing an item, then choose if you want one of the remaining two, or the one you revealed",
  },
  {
    id: "ITEM8",
    name: "Bicycle",
    rarity: "Rare",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: true,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "At the start of your turn, jump to the nearest Pokemon Center in either direction",
  },
  {
    id: "ITEM9",
    name: "Roll Again",
    rarity: "Common",
    useInBattle: true,
    useFromMenu: false,
    useFromBoardDiceRoll: true,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Roll again if you don't like your roll (on board or in battle)",
  },
  {
    id: "ITEM10",
    name: "Roll Two Die",
    rarity: "Epic",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: true,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "In your next board roll, you roll two die instead of 1",
  },
  {
    id: "ITEM11",
    name: "Half Die",
    rarity: "Rare",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: true,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "In your next board roll, roll a 3 sided die instead",
  },
  {
    id: "ITEM12",
    name: "Choose Your Roll",
    rarity: "Legendary",
    useInBattle: true,
    useFromMenu: false,
    useFromBoardDiceRoll: true,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Choose your roll number (on the board or in battle)",
  },
  {
    id: "ITEM13",
    name: "Pokedoll",
    rarity: "Rare",
    useInBattle: true,
    useFromMenu: false,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Automatically escape any non-elite battle",
  },
  {
    id: "ITEM14",
    name: "Grass Incense",
    rarity: "Common",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: true,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "If you land on a pokemon tile this turn, you are much more likely to attract a pokemon of this type",
  },
  {
    id: "ITEM15",
    name: "Fire Incense",
    rarity: "Common",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: true,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "If you land on a pokemon tile this turn, you are much more likely to attract a pokemon of this type",
  },
  {
    id: "ITEM16",
    name: "Water Incense",
    rarity: "Common",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: true,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "If you land on a pokemon tile this turn, you are much more likely to attract a pokemon of this type",
  },
  {
    id: "ITEM17",
    name: "Lightning Incense",
    rarity: "Common",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: true,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "If you land on a pokemon tile this turn, you are much more likely to attract a pokemon of this type",
  },
  {
    id: "ITEM18",
    name: "Fighting Incense",
    rarity: "Common",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: true,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "If you land on a pokemon tile this turn, you are much more likely to attract a pokemon of this type",
  },
  {
    id: "ITEM19",
    name: "Psychic Incense",
    rarity: "Common",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: true,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "If you land on a pokemon tile this turn, you are much more likely to attract a pokemon of this type",
  },
  {
    id: "ITEM20",
    name: "Colourless Incense",
    rarity: "Common",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: true,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "If you land on a pokemon tile this turn, you are much more likely to attract a pokemon of this type",
  },
  {
    id: "ITEM21",
    name: "Incense",
    rarity: "Rare",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: true,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "You are more likely to encounter a wild pokemon on a pokemon tile this turn",
  },
  {
    id: "ITEM22",
    name: "Great Ball",
    rarity: "Rare",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: true,
    useInItemSelection: false,
    autoApply: false,
    text: "Increase catch rate by 1 if used",
  },
  {
    id: "ITEM23",
    name: "Ultra Ball",
    rarity: "Epic",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: true,
    useInItemSelection: false,
    autoApply: false,
    text: "Increase catch rate by 2 if used",
  },
  {
    id: "ITEM24",
    name: "Master Ball",
    rarity: "Legendary",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: true,
    useInItemSelection: false,
    autoApply: false,
    text: "Increase catch rate by 3 if used",
  },
  {
    id: "ITEM25",
    name: "Incubator Glass",
    rarity: "Rare",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: true,
    text: "One part of an Incubator, collecting all 3 will result in the player being able to hatch an egg from one of their pokemon. Players will collect these items in order, so only Glass will be available, until the player gets glass and the base is available. Only one incubator can be made per elite round.",
  },
  {
    id: "ITEM26",
    name: "Incubator Base",
    rarity: "Rare",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: true,
    text: "One part of an Incubator, collecting all 3 will result in the player being able to hatch an egg from one of their pokemon. Players will collect these items in order, so only Glass will be available, until the player gets glass and the base is available. Only one incubator can be made per elite round.",
  },
  {
    id: "ITEM27",
    name: "Incubator Bulb",
    rarity: "Rare",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: true,
    text: "One part of an Incubator, collecting all 3 will result in the player being able to hatch an egg from one of their pokemon. Players will collect these items in order, so only Glass will be available, until the player gets glass and the base is available. Only one incubator can be made per elite round.",
  },
  {
    id: "ITEM28",
    name: "Speedy Start",
    rarity: "Common",
    useInBattle: true,
    useFromMenu: false,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Minimum 4 or higher in the who goes first roll",
  },
  {
    id: "ITEM29",
    name: "Rapid Start",
    rarity: "Rare",
    useInBattle: true,
    useFromMenu: false,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Minimum 5 or higher in the who goes first roll",
  },
  {
    id: "ITEM30",
    name: "Perfect Start",
    rarity: "Epic",
    useInBattle: true,
    useFromMenu: false,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Roll 6 in the who goes first roll",
  },
  {
    id: "ITEM31",
    name: "Small Bag",
    rarity: "Rare",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: true,
    text: "Adds 2 item slots",
  },
  {
    id: "ITEM32",
    name: "Rucksack",
    rarity: "Epic",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: true,
    text: "Adds 4 item slots",
  },
  {
    id: "ITEM33",
    name: "Repel",
    rarity: "Common",
    useInBattle: false,
    useFromMenu: true,
    useFromBoardDiceRoll: true,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "50% less chance of a common encounter on the next grass square",
  },
  {
    id: "ITEM34",
    name: "Super Repel",
    rarity: "Rare",
    useInBattle: false,
    useFromMenu: true,
    useFromBoardDiceRoll: true,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "75% less chance of a common encounter, 25% less chance of a rare encounter on the next grass square",
  },
  {
    id: "ITEM35",
    name: "Max Repel",
    rarity: "Epic",
    useInBattle: false,
    useFromMenu: true,
    useFromBoardDiceRoll: true,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "100% less chance of a common encounter, 50% less chance of a rare encounter on the next grass square",
  },
  {
    id: "ITEM36",
    name: "Dome Fossil",
    rarity: "Rare",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: true,
    text: "Turns into Kabuto if given to the Fossil hunter",
  },
  {
    id: "ITEM37",
    name: "Helix Fossil",
    rarity: "Rare",
    useInBattle: false,
    useFromMenu: false,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: true,
    text: "Turns into Omanyte if given to the Fossil hunter",
  },
  {
    id: "ITEM38",
    name: "Grass Energy",
    rarity: "Common",
    useInBattle: true,
    useFromMenu: true,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Heals a pokemon of this type by 20",
  },
  {
    id: "ITEM39",
    name: "Fire Energy",
    rarity: "Common",
    useInBattle: true,
    useFromMenu: true,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Heals a pokemon of this type by 20",
  },
  {
    id: "ITEM40",
    name: "Water Energy",
    rarity: "Common",
    useInBattle: true,
    useFromMenu: true,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Heals a pokemon of this type by 20",
  },
  {
    id: "ITEM41",
    name: "Lightning Energy",
    rarity: "Common",
    useInBattle: true,
    useFromMenu: true,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Heals a pokemon of this type by 20",
  },
  {
    id: "ITEM42",
    name: "Fighting Energy",
    rarity: "Common",
    useInBattle: true,
    useFromMenu: true,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Heals a pokemon of this type by 20",
  },
  {
    id: "ITEM43",
    name: "Psychic Energy",
    rarity: "Common",
    useInBattle: true,
    useFromMenu: true,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Heals a pokemon of this type by 20",
  },
  {
    id: "ITEM44",
    name: "Colourless Energy",
    rarity: "Common",
    useInBattle: true,
    useFromMenu: true,
    useFromBoardDiceRoll: false,
    useFromPokemonEncounter: false,
    useInItemSelection: false,
    autoApply: false,
    text: "Heals a pokemon of this type by 20",
  },
];

export default items;
