const moves = [
  // Fire
  {
    name: "Ember",
    rarity: "Common",
    type: "Fire",
    damage: 5,
    statusEffect: "Burn",
    statusEffectStrength: 1,
  },
  {
    name: "Flame Wheel",
    rarity: "Common",
    type: "Fire",
    damage: 10,
    statusEffect: null,
    statusEffectStrength: null,
  },
  {
    name: "Fire Spin",
    rarity: "Rare",
    type: "Fire",
    damage: 20,
    statusEffect: "Burn",
    statusEffectStrength: 2,
  },
  {
    name: "Fire Punch",
    rarity: "Rare",
    type: "Fire",
    damage: 30,
    statusEffect: null,
    statusEffectStrength: null,
  },
  {
    name: "Flamethrower",
    rarity: "Epic",
    type: "Fire",
    damage: 40,
    statusEffect: null,
    statusEffectStrength: null,
  },
  {
    name: "Fire Blast",
    rarity: "Legendary",
    type: "Fire",
    damage: 60,
    statusEffect: null,
    statusEffectStrength: null,
  },
  {
    name: "Heat Wave",
    rarity: "Legendary",
    type: "Fire",
    damage: 45,
    statusEffect: "Burn",
    statusEffectStrength: 3,
  },

  // Water
  {
    name: "Bubble",
    rarity: "Common",
    type: "Water",
    damage: 5,
    statusEffect: "Paralyse",
    statusEffectStrength: 1,
  },
  {
    name: "Water Gun",
    rarity: "Common",
    type: "Water",
    damage: 10,
    statusEffect: null,
    statusEffectStrength: null,
  },
  {
    name: "Aqua Jet",
    rarity: "Rare",
    type: "Water",
    damage: 30,
    statusEffect: null,
    statusEffectStrength: null,
  },
  {
    name: "BubbleBeam",
    rarity: "Rare",
    type: "Water",
    damage: 15,
    statusEffect: "Confuse",
    statusEffectStrength: 2,
  },
  {
    name: "Scald",
    rarity: "Epic",
    type: "Water",
    damage: 30,
    statusEffect: "Burn",
    statusEffectStrength: 2,
  },
  {
    name: "Surf",
    rarity: "Epic",
    type: "Water",
    damage: 40,
    statusEffect: null,
    statusEffectStrength: null,
  },
  {
    name: "Hydro Pump",
    rarity: "Legendary",
    type: "Water",
    damage: 60,
    statusEffect: null,
    statusEffectStrength: null,
  },
  {
    name: "Whirlpool",
    rarity: "Legendary",
    type: "Water",
    damage: 50,
    statusEffect: "Confuse",
    statusEffectStrength: 2,
  },

  // Grass
  {
    name: "Vine Whip",
    rarity: "Common",
    type: "Grass",
    damage: 10,
    statusEffect: null,
    statusEffectStrength: null,
  },
  {
    name: "Poison Powder",
    rarity: "Common",
    type: "Grass",
    damage: 0,
    statusEffect: "Poison",
    statusEffectStrength: 2,
  },
  {
    name: "Razor Leaf",
    rarity: "Rare",
    type: "Grass",
    damage: 30,
    statusEffect: null,
    statusEffectStrength: null,
  },
  {
    name: "Mega Drain",
    rarity: "Rare",
    type: "Grass",
    damage: 10,
    statusEffect: "Heal",
    statusEffectStrength: 1,
  },
  {
    name: "Sleep Powder",
    rarity: "Rare",
    type: "Grass",
    damage: 0,
    statusEffect: "Sleep",
    statusEffectStrength: 2,
  },
  {
    name: "Cut",
    rarity: "Epic",
    type: "Grass",
    damage: 40,
    statusEffect: null,
    statusEffectStrength: null,
  },
  {
    name: "Giga Drain",
    rarity: "Legendary",
    type: "Grass",
    damage: 30,
    statusEffect: "Heal",
    statusEffectStrength: 2,
  },
  {
    name: "SolarBeam",
    rarity: "Legendary",
    type: "Grass",
    damage: 50,
    statusEffect: "Paralyse",
    statusEffectStrength: 2,
  },

  // Colourless
  {
    name: "Scratch",
    rarity: "Common",
    type: "Colourless",
    damage: 5,
    statusEffect: null,
    statusEffectStrength: null,
  },
  {
    name: "Headbutt",
    rarity: "Rare",
    type: "Colourless",
    damage: 35,
    statusEffect: null,
    statusEffectStrength: null,
  },
  {
    name: "Slam",
    rarity: "Epic",
    type: "Colourless",
    damage: 45,
    statusEffect: null,
    statusEffectStrength: null,
  },
  {
    name: "Skull Bash",
    rarity: "Epic",
    type: "Colourless",
    damage: 35,
    statusEffect: "Confuse",
    statusEffectStrength: 2,
  },
  {
    name: "Sky Attack",
    rarity: "Epic",
    type: "Colourless",
    damage: 45,
    statusEffect: null,
    statusEffectStrength: null,
  },
];

export default moves;
