const pokemon = [
  {
    id: "BU01",
    name: "Bulbasaur",
    level: 6,
    stage: 1,
    type: "Grass",
    weakness: "Fire",
    rarity: "Rare",
    evolvesInto: "Ivysaur",
    catchRate: 4,
    retreat: 4,
    health: 40,
    attackArray: [null, "Razor Leaf", null, "Scratch", null, "Vine Whip"],
  },
  {
    id: "BU02",
    name: "Bulbasaur",
    level: 12,
    stage: 2,
    type: "Grass",
    weakness: "Fire",
    rarity: "Rare",
    evolvesInto: "Ivysaur",
    catchRate: 4,
    retreat: 4,
    health: 50,
    attackArray: [null, "Razor Leaf", null, "Poison Powder", null, "Vine Whip"],
  },
  {
    id: "BU03",
    name: "Bulbasaur",
    level: 17,
    stage: 3,
    type: "Grass",
    weakness: "Fire",
    rarity: "Rare",
    evolvesInto: "Ivysaur",
    catchRate: 4,
    retreat: 4,
    health: 60,
    attackArray: [null, "Razor Leaf", null, "Mega Drain", null, "Vine Whip"],
  },
  {
    id: "BU04",
    name: "Ivysaur",
    level: 18,
    stage: 4,
    type: "Grass",
    weakness: "Fire",
    rarity: "Epic",
    evolvesInto: "Venusaur",
    catchRate: 3,
    retreat: 3,
    health: 50,
    attackArray: ["Cut", null, "Poison Powder", null, "Razor Leaf", "Vine Whip"],
  },
  {
    id: "BU05",
    name: "Ivysaur",
    level: 23,
    stage: 5,
    type: "Grass",
    weakness: "Fire",
    rarity: "Epic",
    evolvesInto: "Venusaur",
    catchRate: 3,
    retreat: 3,
    health: 60,
    attackArray: ["Sleep Powder", null, "Mega Drain", null, "Razor Leaf", "Vine Whip"],
  },
  {
    id: "BU06",
    name: "Ivysaur",
    level: 30,
    stage: 6,
    type: "Grass",
    weakness: "Fire",
    rarity: "Epic",
    evolvesInto: "Venusaur",
    catchRate: 3,
    retreat: 3,
    health: 70,
    attackArray: ["Cut", null, "Sleep Powder", null, "Razor Leaf", "Vine Whip"],
  },
  {
    id: "BU07",
    name: "Venusaur",
    level: 37,
    stage: 7,
    type: "Grass",
    weakness: "Fire",
    rarity: "Legendary",
    evolvesInto: null,
    catchRate: 2,
    retreat: 2,
    health: 80,
    attackArray: ["Giga Drain", "Sleep Powder", null, "Poison Powder", "Razor Leaf", "Vine Whip"],
  },
  {
    id: "BU08",
    name: "Venusaur",
    level: 45,
    stage: 8,
    type: "Grass",
    weakness: "Fire",
    rarity: "Legendary",
    evolvesInto: null,
    catchRate: 2,
    retreat: 2,
    health: 90,
    attackArray: ["SolarBeam", "Cut", null, "Mega Drain", "Razor Leaf", "Vine Whip"],
  },
  {
    id: "BU09",
    name: "Venusaur",
    level: 56,
    stage: 9,
    type: "Grass",
    weakness: "Fire",
    rarity: "Legendary",
    evolvesInto: null,
    catchRate: 2,
    retreat: 2,
    health: 100,
    attackArray: ["SolarBeam", "Giga Drain", null, "Poison Powder", "Razor Leaf", "Vine Whip"],
  },

  {
    id: "CH01",
    name: "Charmander",
    level: 6,
    stage: 1,
    type: "Fire",
    weakness: "Water",
    rarity: "Rare",
    evolvesInto: "Charmeleon",
    catchRate: 4,
    retreat: 4,
    health: 40,
    attackArray: [null, "Fire Spin", null, "Scratch", null, "Ember"],
  },
  {
    id: "CH02",
    name: "Charmander",
    level: 14,
    stage: 2,
    type: "Fire",
    weakness: "Water",
    rarity: "Rare",
    evolvesInto: "Charmeleon",
    catchRate: 4,
    retreat: 4,
    health: 50,
    attackArray: [null, "Fire Punch", null, "Flame Wheel", null, "Ember"],
  },
  {
    id: "CH03",
    name: "Charmander",
    level: 19,
    stage: 3,
    type: "Fire",
    weakness: "Water",
    rarity: "Rare",
    evolvesInto: "Charmeleon",
    catchRate: 4,
    retreat: 4,
    health: 60,
    attackArray: [null, "Fire Spin", null, "Fire Punch", null, "Ember"],
  },
  {
    id: "CH04",
    name: "Charmeleon",
    level: 17,
    stage: 4,
    type: "Fire",
    weakness: "Water",
    rarity: "Epic",
    evolvesInto: "Charizard",
    catchRate: 3,
    retreat: 3,
    health: 50,
    attackArray: ["Flamethrower", null, "Fire Punch", null, "Flame Wheel", "Ember"],
  },
  {
    id: "CH05",
    name: "Charmeleon",
    level: 24,
    stage: 5,
    type: "Fire",
    weakness: "Water",
    rarity: "Epic",
    evolvesInto: "Charizard",
    catchRate: 3,
    retreat: 3,
    health: 60,
    attackArray: ["Flamethrower", null, "Fire Spin", null, "Fire Punch", "Ember"],
  },
  {
    id: "CH06",
    name: "Charmeleon",
    level: 29,
    stage: 6,
    type: "Fire",
    weakness: "Water",
    rarity: "Epic",
    evolvesInto: "Charizard",
    catchRate: 3,
    retreat: 3,
    health: 70,
    attackArray: ["Flamethrower", null, "Fire Punch", null, "Headbutt", "Ember"],
  },
  {
    id: "CH07",
    name: "Charizard",
    level: 39,
    stage: 7,
    type: "Fire",
    weakness: "Water",
    rarity: "Legendary",
    evolvesInto: null,
    catchRate: 2,
    retreat: 2,
    health: 80,
    attackArray: ["Fire Blast", "Flamethrower", null, "Fire Punch", "Fire Spin", "Ember"],
  },
  {
    id: "CH08",
    name: "Charizard",
    level: 44,
    stage: 8,
    type: "Fire",
    weakness: "Water",
    rarity: "Legendary",
    evolvesInto: null,
    catchRate: 2,
    retreat: 2,
    health: 90,
    attackArray: ["Fire Blast", "Flamethrower", null, "Sky Attack", "Fire Spin", "Ember"],
  },
  {
    id: "CH09",
    name: "Charizard",
    level: 58,
    stage: 9,
    type: "Fire",
    weakness: "Water",
    rarity: "Legendary",
    evolvesInto: null,
    catchRate: 2,
    retreat: 2,
    health: 100,
    attackArray: ["Fire Blast", "Heat Wave", null, "Sky Attack", "Fire Spin", "Ember"],
  },

  {
    id: "SQ01",
    name: "Squirtle",
    level: 7,
    stage: 1,
    type: "Water",
    weakness: "Lightning",
    rarity: "Rare",
    evolvesInto: "Wartortle",
    catchRate: 4,
    retreat: 4,
    health: 40,
    attackArray: [null, "BubbleBeam", null, "Scratch", null, "Bubble"],
  },
  {
    id: "SQ02",
    name: "Squirtle",
    level: 11,
    stage: 2,
    type: "Water",
    weakness: "Lightning",
    rarity: "Rare",
    evolvesInto: "Wartortle",
    catchRate: 4,
    retreat: 4,
    health: 50,
    attackArray: [null, "Aqua Jet", null, "Water Gun", null, "Bubble"],
  },
  {
    id: "SQ03",
    name: "Squirtle",
    level: 18,
    stage: 3,
    type: "Water",
    weakness: "Lightning",
    rarity: "Rare",
    evolvesInto: "Wartortle",
    catchRate: 4,
    retreat: 4,
    health: 60,
    attackArray: [null, "BubbleBeam", null, "Aqua Jet", null, "Bubble"],
  },
  {
    id: "SQ04",
    name: "Wartortle",
    level: 17,
    stage: 4,
    type: "Water",
    weakness: "Lightning",
    rarity: "Epic",
    evolvesInto: "Blastoise",
    catchRate: 3,
    retreat: 3,
    health: 50,
    attackArray: ["Surf", null, "Aqua Jet", null, "Bubble", "Water Gun"],
  },
  {
    id: "SQ05",
    name: "Wartortle",
    level: 25,
    stage: 5,
    type: "Water",
    weakness: "Lightning",
    rarity: "Epic",
    evolvesInto: "Blastoise",
    catchRate: 3,
    retreat: 3,
    health: 60,
    attackArray: ["Scald", null, "Aqua Jet", null, "BubbleBeam", "Water Gun"],
  },
  {
    id: "SQ06",
    name: "Wartortle",
    level: 30,
    stage: 6,
    type: "Water",
    weakness: "Lightning",
    rarity: "Epic",
    evolvesInto: "Blastoise",
    catchRate: 3,
    retreat: 3,
    health: 70,
    attackArray: ["Surf", null, "Scald", null, "Aqua Jet", "Water Gun"],
  },
  {
    id: "SQ07",
    name: "Blastoise",
    level: 38,
    stage: 7,
    type: "Water",
    weakness: "Lightning",
    rarity: "Legendary",
    evolvesInto: null,
    catchRate: 2,
    retreat: 2,
    health: 80,
    attackArray: ["Hydro Pump", "Surf", null, "Aqua Jet", "BubbleBeam", "Water Gun"],
  },
  {
    id: "SQ08",
    name: "Blastoise",
    level: 46,
    stage: 8,
    type: "Water",
    weakness: "Lightning",
    rarity: "Legendary",
    evolvesInto: null,
    catchRate: 2,
    retreat: 2,
    health: 90,
    attackArray: ["Hydro Pump", "Scald", null, "Slam", "Aqua Jet", "Water Gun"],
  },
  {
    id: "SQ09",
    name: "Blastoise",
    level: 55,
    stage: 9,
    type: "Water",
    weakness: "Lightning",
    rarity: "Legendary",
    evolvesInto: null,
    catchRate: 2,
    retreat: 2,
    health: 100,
    attackArray: ["Hydro Pump", "Whirlpool", null, "Skull Bash", "BubbleBeam", "Water Gun"],
  },
];

// Derive maxHealth from base health so it is always correct.
const pokemonWithMaxHealth = pokemon.map((p) => ({
  ...p,
  maxHealth: p.health,
}));

export default pokemonWithMaxHealth;
